apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kibana-sample
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: kibana-sample-kb-http
    weight: 100
  port:
    targetPort: proxy
  wildcardPolicy: None
