---
apiVersion: v1
kind: Secret
metadata:
  name: heartbeat-config
stringData:
  beat.yml: |-
    heartbeat.monitors:
    - type: http
      schedule: '@every 5s'
      hosts: ["nginx-ex.mesh-external.svc:8080"]
...