---
apiVersion: v1
kind: Secret
metadata:
  name: heartbeat-config
stringData:
  beat.yml: |-
    heartbeat.monitors:
    - type: http
      schedule: '@every 5s'
      hosts: ["nginx-ex.mesh-external.svc:8080"]
    output.elasticsearch:
      hosts: http://elasticsearch-sample-es-http.{{ .Release.Namespace }}.svc.cluster.local:9200
    setup.kibana:
      host: kibana-sample-kb-http.{{ .Release.Namespace }}.svc.cluster.local:5601
...