apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: heartbeat
  namespace: {{ .Release.Namespace }}
  labels:
    app: heartbeat-build
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: docker.elastic.co/beats/heartbeat:7.6.2
    from:
      kind: DockerImage
      name: docker.elastic.co/beats/heartbeat:7.6.2
    importPolicy: {}
    name: 7.6.2
    referencePolicy:
      type: Source
