---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heartbeat
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: heartbeat
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heartbeat