---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: kibana
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oauth-proxy

