apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: kibana
  config:
    xpack.security.enabled: false
  count: 1
  elasticsearchRef:
    name: elasticsearch-sample
  http:
    service:
      metadata:
        creationTimestamp: null
        annotations:
          service.alpha.openshift.io/serving-cert-secret-name: kibana-tls
      spec:
        ports:
          - name: proxy
            protocol: TCP
            port: 9091
            targetPort: 9091
        selector:
          common.k8s.elastic.co/type: kibana
          kibana.k8s.elastic.co/name: kibana-sample
        clusterIP: None
        type: ClusterIP
        sessionAffinity: None
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    metadata:
      creationTimestamp: null
      labels:
        maistra.io/expose-route: 'true'
    spec:
      automountServiceAccountToken: true
      serviceAccountName: kibana
      volumes:
        - name: kibana-tls
          secret:
            secretName: kibana-tls
            defaultMode: 42
        - name: kibana-proxy
          secret:
            secretName: kibana-proxy
            defaultMode: 42
        - name: configmap-trusted-ca-bundle
          configMap:
            name: trusted-ca-bundle
            defaultMode: 420
      containers:
      - name: kibana
        resources:
          requests:
            cpu: "1"
            memory: 4Gi
        readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 5601
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
      - name: proxy
        args:
        - '-provider=openshift'
        - '-pass-basic-auth=false'
        - '-https-address=:9091'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:5601'
        - '-openshift-sar={"namespace":"{{ .Release.Namespace }}","resource":"services","verb":"list"}'
        - '-openshift-delegate-urls={"/": {"namespace":"{{ .Release.Namespace }}","resource":"services","verb":"list"}}'
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
        - '-openshift-service-account=kibana'
        - '-openshift-ca=/etc/configmaps/trusted-ca-bundle/ca-bundle.crt'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-skip-auth-regex=^/metrics'
        image: 'quay.io/openshift/origin-oauth-proxy:4.6'
        ports:
          - containerPort: 9091
            name: proxy
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
          - mountPath: /etc/tls/private
            name: kibana-tls
          - mountPath: /etc/proxy/secrets
            name: kibana-proxy
          - name: configmap-trusted-ca-bundle
            mountPath: /etc/configmaps/trusted-ca-bundle
            readOnly: true
  version: 7.6.2