apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: kibana-kb-http
    weight: 100
  port:
    targetPort: proxy
  wildcardPolicy: None
